# Generated by Django 3.0.7 on 2020-06-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_conocimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arma', models.CharField(max_length=50)),
                ('id_soldado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_conocimiento.Soldado')),
            ],
        ),
    ]
